# Generated by Django 5.2.3 on 2025-06-20 19:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('YOGA', 'Yoga'), ('ZUMBA', 'Zumba'), ('HIIT', 'HIIT')], help_text='Type of fitness class', max_length=20)),
                ('datetime_utc', models.DateTimeField(help_text='Class date and time in UTC')),
                ('instructor', models.CharField(help_text='Name of the class instructor', max_length=100)),
                ('total_slots', models.PositiveIntegerField(help_text='Total number of available slots for this class', validators=[django.core.validators.MinValueValidator(1)])),
                ('available_slots', models.PositiveIntegerField(help_text='Number of slots currently available for booking', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fitness Class',
                'verbose_name_plural': 'Fitness Classes',
                'ordering': ['datetime_utc'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Name of the client making the booking', max_length=100)),
                ('client_email', models.EmailField(help_text='Email address of the client', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', help_text='Current status of the booking', max_length=10)),
                ('booking_time', models.DateTimeField(auto_now_add=True, help_text='When this booking was made (UTC)')),
                ('fitness_class', models.ForeignKey(help_text='The fitness class being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.fitnessclass')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_time'],
                'unique_together': {('fitness_class', 'client_email')},
            },
        ),
    ]
